// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 格式化配置
 */
export type FormatConfig = { indent_spaces: number; blank_lines_between_paragraphs: number }

export type OverridableConfig = { fmt: FormatConfig }

export type RootConfig = { workspace: WorkspaceConfig | null }

export type WorkspaceConfig = { cache_dir: string; novelsaga_dir: string }

export type _NovelSagaConfig = { workspace: WorkspaceConfig | null; fmt: FormatConfig }
