// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a metadata entity with id, type, namespace, frontmatter, and body.
 */
export type MetadataEntity = { 
/**
 * Unique identifier for the metadata entity
 */
id: string, 
/**
 * Type of the metadata entity (renamed from type_ in JSON)
 */
type: string, 
/**
 * Namespace grouping for the entity
 */
namespace: string, 
/**
 * Frontmatter data stored as JSON value
 * Frontmatter data stored as JSON value
 */
frontmatter: Record<string, any>, 
/**
 * Body content as string
 */
body: string, };
